# ---------------------------------------------------------------------------------
# Security Check
#
# This workflow runs Bandit to perform a security scan on the codebase.
#
# It is triggered:
# - on every push and pull request,
# - nightly at 04:00 UTC,
# - manually via workflow dispatch.
# ---------------------------------------------------------------------------------

name: Security Check

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  security-check:
    name: Run Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r pyledger -ll
