on:
  # For all pushes run the tests
  push:
  # Also trigger on pull_request
  pull_request:
  # Schedule daily run at 3:48 AM UTC
  schedule:
  - cron: '48 3 * * *'
  workflow_dispatch:

name: Unit/Integration Tests

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: python:latest
    if: |
        (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
        (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v4

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup virtualenv
        run: |
          python -V  # Print out python version for debugging
          pip install virtualenv pytest
          virtualenv venv
          . venv/bin/activate

      - name: Install dependencies
        run: pip install coverage pytest pandas setuptools .

      - name: Install package
        run: python setup.py develop

      - name: Run tests
        run: coverage run -m pytest -W error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-upload

