# ---------------------------------------------------------------------------------
# Unit/Integration Tests
#
# This workflow runs unit and integration tests.
#
# It is triggered:
# - on every push and pull request,
# - nightly at 04:00 UTC,
# - manually via workflow dispatch.
# ---------------------------------------------------------------------------------

name: Unit/Integration Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "40 3 * * *"
  workflow_dispatch:

jobs:
  tests:
    name: Run Unit/Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pytest coverage setuptools .

      - name: Run tests with coverage
        run: coverage run -m pytest -W error

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-upload
